#!/bin/bash

function makeImage() {
  echo '<a href="'$1'"><img src="'$2'" width=250></img></a>'
}

echo "## Gallery"
echo
while read line; do
  makeImage $line
done < assets/gallery.txt
echo '<a href="'https://github.com/samchristywork/neotmux'"><img src="'https://raw.githubusercontent.com/samchristywork/neotmux/main/assets/callgraph.png'" width=760></img></a>'
echo
