#!/bin/bash

echo "## Gallery"
echo
echo '<a href="https://github.com/samchristywork/hexdump-colorful">       <img width=250 src="https://raw.githubusercontent.com/samchristywork/hexdump-colorful/main/example/color_key.png"></img></a>'
echo '<a href="https://github.com/samchristywork/hexdump-colorful">       <img width=250 src="https://raw.githubusercontent.com/samchristywork/hexdump-colorful/main/example/selecting_classes.png"></img></a>'
echo '<a href="https://github.com/samchristywork/tree-viewer">            <img width=250 src="https://raw.githubusercontent.com/samchristywork/tree-viewer/main/assets/screenshot-light.png"></img></a>'

echo '<a href="https://github.com/samchristywork/thyme">                  <img width=250 src="https://raw.githubusercontent.com/samchristywork/thyme/main/assets/screenshot.png"></img></a>'
echo '<a href="https://github.com/samchristywork/terminal-calendar">      <img width=250 src="https://raw.githubusercontent.com/samchristywork/terminal-calendar/main/sample_annotated.png"></img></a>'
echo '<a href="https://github.com/samchristywork/log-viewer">             <img width=250 src="https://raw.githubusercontent.com/samchristywork/log-viewer/main/res/screenshot.png"></img></a>'

echo '<a href="https://github.com/samchristywork/minesweeper">            <img width=250 src="https://raw.githubusercontent.com/samchristywork/minesweeper/main/screenshots/image_1.png"></img></a>'
echo '<a href="https://github.com/samchristywork/boids">                  <img width=250 src="https://raw.githubusercontent.com/samchristywork/boids/main/res/screenshot.png"></img></a>'
echo '<a href="https://github.com/samchristywork/transclude">             <img width=250 src="https://raw.githubusercontent.com/samchristywork/transclude/32926b1161d298a278e23e8438012203b9d6133e/assets/sample_graph.svg"></img></a>'

echo '<a href="https://github.com/samchristywork/boids">                  <img width=760 src="https://raw.githubusercontent.com/samchristywork/boids/main/res/screenshot.png"></img></a>'

echo '<a href="https://github.com/samchristywork/creature-simulation">    <img width=250 src="https://raw.githubusercontent.com/samchristywork/creature-simulation/main/resources/screenshot-1.png"></img></a>'
echo '<a href="https://github.com/samchristywork/jigsaw-puzzle-generator"><img width=250 src="https://raw.githubusercontent.com/samchristywork/jigsaw-puzzle-generator/a90ab364772c3a3869c454a4367be9493bed8600/res/board.svg"></img></a>'
echo '<a href="https://github.com/samchristywork/turing-machine">         <img width=250 src="https://raw.githubusercontent.com/samchristywork/turing-machine/f208795a1995fdc0241c05e9102e975db347db0f/res/busy_beaver.svg"></img></a>'

echo '<a href="https://github.com/samchristywork/neotmux">                <img width=760 src="https://raw.githubusercontent.com/samchristywork/neotmux/main/assets/callgraph.png"></img></a>'
echo
