#!/bin/bash

echo Language summary generated on
date
echo

cat data/languages | \
  cut -f2 -d: | \
  sed 's/,/\n/g' | \
  sort | \
  uniq -c | \
  sed 1d | \
  awk 'BEGIN{
    print "Language\tCount\tPercentage"
    print "--------\t-----\t----------"
  }
  {
    if ($2 == "HTML") {
      next
    }

    if ($2 == "CSS") {
      next
    }

    if ($2 == "Makefile") {
      next
    }

    percentage=$1*100/'$(wc -l < data/languages)'
    if (percentage > 5) {
      printf "%s\t%d\t%2.2f%%\n", $2, $1, percentage
    }
  }' | \
  column -t -s'	' -o' | '
echo
